### ISSUE TITLE
报错Unknown data type (18) for message dispatching

### ISSUE THREAD

**Issue by dqss** [SuperMonster003/AutoJs6#100]
Unknown data type (18) for message dispatching

**Comment by SuperMonster003** [comment]
已收到反馈, 将于下周三前修复上述问题.

_Sent from my XQ-DQ72 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dqss** [comment]
马上先处理这个问题，完全没法用了，超过150行就这样

**Comment by dqss** [comment]
打错了，是麻烦

**Comment by SuperMonster003** [comment]
#91 #92 #93 #94
