### ISSUE TITLE
runtime.requestPermissions 报错 不存在方法，

### ISSUE THREAD

**Issue by diuchouni** [SuperMonster003/AutoJs6#104]
14:37:15.621/E: TypeError: 对象 org.autojs.autojs.runtime.ScriptRuntime@3bfbb59 不存在方法 requestPermissions. (/data/user/0/org.autojs.autojs6/cache/tmp-scripts/tmp-1689575834263.js#1)
TypeError: 对象 org.autojs.autojs.runtime.ScriptRuntime@3bfbb59 不存在方法 requestPermissions.
    at /data/user/0/org.autojs.autojs6/cache/tmp-scripts/tmp-1689575834263.js:1:0

**Comment by SuperMonster003** [comment]
感谢反馈.

6.3.3 已尝试修复上述问题, 如问题复现, 可继续反馈.
