### ISSUE TITLE
删除脚本内容时闪退

### ISSUE THREAD

**Issue by m1mark** [SuperMonster003/AutoJs6#106]
Version: 1999
Android: 33
ANR_EXCEPTION: ANR Input dispatching timed out (8c88cec org.autojs.autojs6/org.autojs.autojs.ui.main.MainActivity (server) is not responding. Waited 5001ms for MotionEvent(action=DOWN))
java.lang.Object.wait(Native Method)
java.lang.Object.wait(Object.java:442)
java.lang.Object.wait(Object.java:568)
okhttp3.internal.http2.Http2Stream.waitForIo$okhttp(Http2Stream.kt:744)
okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:401)
okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
okio.RealBufferedSource.read(RealBufferedSource.kt:189)
okio.RealBufferedSource.exhausted(RealBufferedSource.kt:197)
okio.InflaterSource.refill(InflaterSource.kt:112)
okio.InflaterSource.readOrInflate(InflaterSource.kt:76)
okio.InflaterSource.read(InflaterSource.kt:49)
okio.GzipSource.read(GzipSource.kt:69)
okio.RealBufferedSource.read(RealBufferedSource.kt:189)
okio.ForwardingSource.read(ForwardingSource.kt:27)
retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
java.io.InputStreamReader.read(InputStreamReader.java:180)
java.io.BufferedReader.fill(BufferedReader.java:172)
java.io.BufferedReader.read(BufferedReader.java:193)
org.autojs.autojs.network.UpdateChecker.getVersionInfoByBlob(UpdateChecker.java:202)
org.autojs.autojs.network.UpdateChecker.getVersionInfo(UpdateChecker.java:165)
org.autojs.autojs.network.UpdateChecker.-$$Nest$mgetVersionInfo(Unknown Source:0)
org.autojs.autojs.network.UpdateChecker$1.onNext(UpdateChecker.java:118)
org.autojs.autojs.network.UpdateChecker$1.onNext(UpdateChecker.java:104)
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
android.os.Handler.handleCallback(Handler.java:942)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loopOnce(Looper.java:210)
android.os.Looper.loop(Looper.java:299)
android.app.ActivityThread.main(ActivityThread.java:8261)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by SuperMonster003** [comment]
脚本的代码量是否过于庞大.

传统的代码编辑器在代码量 (即文件内容大小) 过大时, 将出现异常甚至导致 Auto.js 强制关闭.
