### ISSUE TITLE
请教一下，AutoJs6-VSCode-Extension 的历史版本在哪里下载?

### ISSUE THREAD

**Issue by Goodgoodstudy007** [SuperMonster003/AutoJs6#107]
请教一下，AutoJs6-VSCode-Extension 的历史版本在哪里下载?在vscode插件商店，找到的都是最新的版本.

**Comment by dqss** [comment]
同求

**Comment by CuteLicense** [comment]
卸载时界面可以选重装历史版本

**Comment by SuperMonster003** [comment]
提供 3 种历史版本安装方法.

---

### 1. 使用 VSCode 插件直接安装历史版本

安装最新版本插件, 在插件的右侧详情窗口, 卸载按钮处点击下拉箭头, 选择 `Install Another Version (安装另一个版本)`:

![image](https://github.com/SuperMonster003/AutoJs6/assets/30370009/78b1160b-8ad8-44c0-9341-ac721fc3db1a)

### 2. 在 Visual Studio 插件市场安装历史版本

点击 VSCode 插件详情的 `Marketplace (市场)`:

![image](https://github.com/SuperMonster003/AutoJs6/assets/30370009/e7e04875-5efb-4cb8-b833-efbc323bb467)

点击 `Version History (版本历史)`:

![image](https://github.com/SuperMonster003/AutoJs6/assets/30370009/7483dfdc-4b4d-41a7-a24b-600520f496ba)

选择一个历史版本下载并安装.

安装 vsix 格式的插件, 可打开 VSCode 的插件窗口 (CTRL + SHIFT + X), 右侧三点按钮, 选择 `Install from VSIX (从 VSIX 安装)`, 定位到刚才下载的 vsix 文件即可完成安装.

### 3. 在当前项目的发行版本页面下载历史版本

访问 http://vscext-project.autojs6.com/releases, 选择一个历史版本:

![image](https://github.com/SuperMonster003/AutoJs6/assets/30370009/2b42450a-269f-46d6-85c9-85bc9be5f1b3)
