### ISSUE TITLE
使用v6.3.2遇到打包插件未安装的问题?

### ISSUE THREAD

**Issue by Goodgoodstudy007** [SuperMonster003/AutoJs6#108]
请教一下，以前，今年3月份的时候用过一次，点击一下安卓小机器人就可以顺利打包，现在再来用，同样点击安卓小机器人，会提示“打包插件未安装”。根据提示下载插件后，点安卓小机器人，打包是可以打包，但是没有以前那些选择 加密 和 启动图标界面了，只有一个路径选择。这是什么问题呢？多有打扰了。

**Comment by diuchouni** [comment]
因为没有正式的打包插件。 准确的说打包不了

**Comment by SuperMonster003** [comment]
AutoJs6 没有提供上述打包选项, 因为项目使用的是传统 Auto.js 4.x 的打包插件.

如需获得更好的打包体验, 可尝试 [AutoX](https://github.com/kkevsekk1/AutoX) 或 [Auto.js Pro](https://pro.autojs.org/) 等版本.

**Comment by Goodgoodstudy007** [comment]
> AutoJs6 没有提供上述打包选项, 因为项目使用的是传统 Auto.js 4.x 的打包插件.
> 
> 如需获得更好的打包体验, 可尝试 [AutoX](https://github.com/kkevsekk1/AutoX) 或 [Auto.js Pro](https://pro.autojs.org/) 等版本.

AutoX我也使用过，不如AutoJs6好用，Auto.js Pro真是扯淡，大厂的软件都用不了，真不晓得有什么意义。只是AutoJs6打包好像有点问题，经常出现用Vscode调试输出与apk安装后运行输出不一样的情况。
