### ISSUE TITLE
运行某个自定义函数就报错，断开连接。但是单独拿出来新建js文件就不会报错

### ISSUE THREAD

**Issue by 422557374** [SuperMonster003/AutoJs6#109]
新建js文件单独运行正常，组合到一个js文件里面即使不调用这个函数也会报错，断开连接
![image](https://github.com/SuperMonster003/AutoJs6/assets/69720910/703aca27-013d-4850-91f9-e0cfd95a6271)

15:23:37.373/E: Unknown data type (0) for message dispatching

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/AutoJs6/issues/91 https://github.com/SuperMonster003/AutoJs6/issues/92 https://github.com/SuperMonster003/AutoJs6/issues/93 https://github.com/SuperMonster003/AutoJs6/issues/94 #100
