### ISSUE TITLE
vscode中使用save命令无法保存到手机

### ISSUE THREAD

**Issue by a4youma** [SuperMonster003/AutoJs6#11]
三种连接方式都不能保存vs中的代码到手机

**Comment by getda** [comment]
选择保存到指定设备是可以的

**Comment by SuperMonster003** [comment]
AutoJs6 6.3.3 已尝试修复上述问题, 更新使用后如问题复现, 可继续反馈. 此议题暂时关闭.

另, 需根据 AutoJs6 的提示更新 VSCode 插件到要求的最低版本才能正常使用插件功能.
