### ISSUE TITLE
 new com.stardust.autojs.execution.ExecutionConfig()问题

### ISSUE THREAD

**Issue by leechor** [SuperMonster003/AutoJs6#113]
`  let config = new com.stardust.autojs.execution.ExecutionConfig();`
19:29:07.304/E: TypeError: [JavaPackage com.stardust.autojs.execution.ExecutionConfig] 是 object 而非函数. (file:/storage/emulated/0/脚本/ext-timers.js#141)
TypeError: [JavaPackage com.stardust.autojs.execution.ExecutionConfig] 是 object 而非函数.
在autojs(及autox.js)上是可以使用的.

**Comment by leechor** [comment]
[ext-timers.txt](https://github.com/SuperMonster003/AutoJs6/files/12182896/ext-timers.txt)

**Comment by SuperMonster003** [comment]
解决方案:

a. 使用 `new org.autojs.autojs.execution.ExecutionConfig();` 替代

b. 开启 AutoJs6 的设置选项 "Java 类名 4.x 版本兼容"

> 注: 
>
> AutoJs6 相较于开源版本 4.x 变更了大量包名及类名, 因此无法保证直接调用内部包名的效果与开源版本完全相同, 甚至可能出现访问异常.
>
> AutoJs6 仅保证内置 JavaScript 全局模块的最大兼容.

**Comment by leechor** [comment]
> 解决方案:
> 
> a. 使用 `new org.autojs.autojs.execution.ExecutionConfig();` 替代
> 
> b. 开启 AutoJs6 的设置选项 "Java 类名 4.x 版本兼容"
> 
> > 注:
> > AutoJs6 相较于开源版本 4.x 变更了大量包名及类名, 因此无法保证直接调用内部包名的效果与开源版本完全相同, 甚至可能出现访问异常.
> > AutoJs6 仅保证内置 JavaScript 全局模块的最大兼容.

好的,谢谢!
