### ISSUE TITLE
没事了

### ISSUE THREAD

**Issue by diuchouni** [SuperMonster003/AutoJs6#114]
希望添加 floaty.requestPermission() 和 floaty.checkPermission() 这两权限

**Comment by happyme531** [comment]
+1

参照 http://doc.autoxjs.com/#/floaty

**Comment by SuperMonster003** [comment]
```js
floaty.hasPermission(); /* 是否已授予权限. */
floaty.requestPermission(); /* 跳转至权限设置页面. */
floaty.ensurePermission(); /* 确保已授予权限, 否则抛出异常 (v6.3.4+). */
```

**Comment by diuchouni** [comment]
> ```js
> floaty.hasPermission(); /* 是否已授予权限. */
> floaty.requestPermission(); /* 跳转至权限设置页面. */
> floaty.ensurePermission(); /* 确保已授予权限, 否则抛出异常 (v6.3.4+). */
> ```

好的。一时没注意。
