### ISSUE TITLE
当列表的按钮text有变化时就没法点击了

### ISSUE THREAD

**Issue by yikus-tjq** [SuperMonster003/AutoJs6#123]
```js
// 获取列表
const userList = id("xxx.xxx:id/euf").findOne().children()
for (let i = 0; i < userList.length; i++) {
    let child = userList[i];
    let btn = child.findOne(id("xxx.xxx:id/etv"))
    if (["回关"].includes(btn?.text() ?? '')) {
        btn.click() // 按钮的text为“回关”点击按钮后 text变成了 “去私聊”
        sleep(1000)
        btn.click() // 在这里点击的时候 会出错，他没有点击原来的按钮 而是点击的是 列表 第一项的 去私聊 不是当前按钮的 去私聊
    }
}
```

**Comment by yikus-tjq** [comment]
我暂时解决的方法:
id("xxx.xxx:id/euf").findOne().child(i).findOne(id("xxx.xxx:id/etv")).click()
这样就可以点当前按钮的 去私聊

**Comment by yikus-tjq** [comment]
他这个列表是个 虚拟列表

**Comment by sucutey** [comment]
function main() {
    let user_list = pickup(id(user_id), "{}"); //用户昵称控件集合
    user_list && user_list.forEach(item => {
            let user_name = item.text(); //用户昵称
            while (true) {
//compass 表示可用的罗盘参数
                let btn_text = pickup(id(user_id).text(user_name), compass, "text"); //按钮文本
                btn_text == "关注" && pickup(id(user_id).text(user_name), compass, "click") //点击关注
                if (btn_text == "去私聊") {
                    pickup(id(user_id).text(user_name), compass, "click"); //点击私聊
                    back(); //返回
                    log("---循环---");
                    break; //退出
                }
           })
    }
利用罗盘偏移定位按钮控件，再点击即可

**Comment by SuperMonster003** [comment]
按钮文本变化之后, 可能不仅仅是把原有控件的 text / desc 改变了, 而是整个控件改变.

因此不能用缓存的 btn, 需要再筛选一次控件.

```js
 if (["回关"].includes(btn?.text() ?? '')) {
     child.findOne(id("xxx.xxx:id/etv")).click();
     sleep(1000)
     child.findOne(id("xxx.xxx:id/etv")).click();
 }
```

如果希望避免空指针异常, 建议使用 pickup.

另外, `?.` 和 `??` 这种语法, 确定在 AutoJs6 上可以使用吗.

**Comment by yikus-tjq** [comment]
写了个 gulp，实时将脚本转成 es5语法
