### ISSUE TITLE
什么时候支持es6的更多的新特性

### ISSUE THREAD

**Issue by sucutey** [SuperMonster003/AutoJs6#135]
展开语法...arr
不定长参数...args
默认传参fn(arg='default'){}
这三个足够用了
天下苦es5久矣

**Comment by yikus-tjq** [comment]
这个 我估计得等 java啥时候能够支持了，但是有办法解决 通过babel 实时转换

**Comment by SuperMonster003** [comment]
这个只能等 Rhino 升级, 或者替换其他引擎 (如 Node.js).

目前是没办法的.
