### ISSUE TITLE
Response.body.contentType  返回类型错误

### ISSUE THREAD

**Issue by hlyzhot** [SuperMonster003/AutoJs6#142]
按照文档，"contentType { string } 当前响应的内容类型"是string类型，现在返回的是function contentType() {/*
okhttp3.MediaType contentType()
*/}
这个字段是否以弃用。

**Comment by SuperMonster003** [comment]
`6.4.1` (稍后发布) 将尝试修复上述问题, 如问题复现, 可继续反馈.
