### ISSUE TITLE
emit 传参

### ISSUE THREAD

**Issue by tlkt** [SuperMonster003/AutoJs6#144]
![image](https://github.com/SuperMonster003/AutoJs6/assets/4469921/939a92bb-28cf-485d-b7ce-d245da0158f4)
![image](https://github.com/SuperMonster003/AutoJs6/assets/4469921/f03f4fef-e69b-4325-91ee-cdb0f1b603cb)

**Comment by SuperMonster003** [comment]
使用以下测试代码未能复现上述问题.

```js
let emitter = events.emitter();
emitter.on("foo", (a, b) => log(a, b));
setTimeout(() => emitter.emit("foo", 1, 2), 1e3);
```

后续版本如问题复现, 可继续反馈.
