### ISSUE TITLE
使用events.observeNotification()报错

### ISSUE THREAD

**Issue by wingswing1** [SuperMonster003/AutoJs6#145]
提示
08:43:42.930/E: Wrapped android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want? (/storage/emulated/0/脚本/w.js#1) Wrapped android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want? at /storage/emulated/0/脚本/w.js:1:0

**Comment by zanyatta** [comment]
通病，重新授予无障碍权限。
