### ISSUE TITLE
有办法不用识图的办法,获取文字颜色,或者根据文字颜色来定位元素吗

### ISSUE THREAD

**Issue by JKstring** [SuperMonster003/AutoJs6#152]
请问有没有办法根据文字颜色来定位,或者获取View中特殊颜色的字吗,比如寻找界面上有红色"文章"两个字的View,或者同一个View中,被标红的文字内容

**Comment by sucutey** [comment]
看不懂你在说什么，既然能获取到控件的文本，就代表你能找到控件，还管他文本什么颜色？

**Comment by JKstring** [comment]
@sucutey 因为他的一段话在一个View中,这一段话中只有带标红的是关键字文本,我需要这个关键字文本,问题不在于定位,但是如果实在获取不到颜色信息,能定位也能变向的解决一些问题 ,这不是一个关于找控件的问题,而是数据处理的问题,所以有办法能获取吗?

**Comment by sucutey** [comment]
正则匹配，字符串截取和分割，这些不是最基础的js吗

**Comment by JKstring** [comment]
@sucutey 如果能用简单的正则表达式的话就没那么麻烦了,他的文本是完全的自然语言,但是会把关键信息标红,类似于用户协议,法律规定要把用户和平台的义务责任重点标出来,但是每一家的用户协议并不一样,且就算相同义务责任,每家描述都不完全一样,所以没法通过正则匹配.目前我就只能想到图片识别或者二值化提取红色文字,再进行OCR,或者给ChatGPT之类的AI进行语言理解,但这两种方式显然效率会很低,如果能直接提取到标红文字或者别的样式信息会非常方便.我找过相关的文档,但是还是不清楚有没有返回类似html或者xml界面信息之类的接口,我没有安卓和java相关的开发经验,不清楚是否能通过事件拿到页面信息.

**Comment by sucutey** [comment]
协议写好一般不会频繁改，会作为静态资源存在本地，反编译一下apk就看到了
![Screenshot_20231004_132505](https://github.com/SuperMonster003/AutoJs6/assets/143495929/c773a8a8-047b-410b-b5b6-b095bd9a1cd2)

**Comment by sucutey** [comment]
![Screenshot_2023_1004_132628](https://github.com/SuperMonster003/AutoJs6/assets/143495929/a0346dde-928f-40a3-85e5-cf57549ad2bf)

**Comment by JKstring** [comment]
@sucutey 如果只是一家的话我是不介意这样,只是我要的这种数据只是格式类似用户协议,但是他是动态的,类似于一个APP,将各种程序的用户协议收集在一起了,不定时增加减少,无法预知他会增加哪些减少哪些,获取到数据后还需要后续手机自动化操作,且数据也只能在他APP内获取,单单写死规则难以处理. 或许获取到ajax请求也能得到数据,但是我想这对autojs来说有点超纲了,且也有可能涉及到加密的问题,直接请求他的接口还有封号的危险,最后还是觉得得到页面的html/xml可能性更大点,也能方便其他使用autojs的用户,所以才在这里问一下是否有类似的功能,或者有什么办法能处理这种情况.当然如果能有类似于hook/监听 ajax请求之类的操作来得到数据极好的,只是最好能较为独立的运行,如果还需要弄个服务器代理抓包,似乎麻烦程度还在OCR和AI识别之上...

**Comment by SuperMonster003** [comment]
目前没有想到可行的办法.

**Comment by JKstring** [comment]
> 目前没有想到可行的办法.

谢谢你的回复,请问有没有办法获取到有aira-hidden标记内容的信息,我有一个APP无法获取到text值,据我了解可能是因为被标记了aira-hidden属性,他在界面中可以显示出来,却无法被获取,请问是否有可行办法.

**Comment by JKstring** [comment]
> 能抓接口就抓接口

我会尝试用别的方法实现,谢谢
