### ISSUE TITLE
device.height 结果错误

### ISSUE THREAD

**Issue by hduwhyso** [SuperMonster003/AutoJs6#160]
AJ6版本：6.4.0

代码：log(device.height,device.width)

下图是我手机：
![124e11b5b0d8b90d4bf2832b0fefc62](https://github.com/SuperMonster003/AutoJs6/assets/67532273/8b77dd0d-a835-43fb-ae5c-4056e2439134)
下图是AJX的结果：
![f3d340b7e7b1d91dacb3d277d53655c](https://github.com/SuperMonster003/AutoJs6/assets/67532273/1df81e39-5e6c-4c5d-9337-5c182aec663a)
下图是AJ6的结果：
![5d8ac4ff9fa806a17cfce6756585f16](https://github.com/SuperMonster003/AutoJs6/assets/67532273/54c119b1-25fd-4aa2-8c09-d761a79ef532)

**Comment by wingswing1** [comment]
同样问题，那不重复反馈了，K50高度3200获取的是3096

**Comment by SuperMonster003** [comment]
@wingswing1 6.4.1 依然有上述问题吗.

_Sent from my XQ-DQ72 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wingswing1** [comment]
> @wingswing1 6.4.1 依然有上述问题吗.
> 
> _Sent from my XQ-DQ72 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

我还没更新（6.4.0），如有问题再反馈

**Comment by hduwhyso** [comment]
6.4.1已实测已解决此问题
