### ISSUE TITLE
pickup使用$［］和w｛｝获取控件或者控件文本集合会报错

### ISSUE THREAD

**Issue by sucutey** [SuperMonster003/AutoJs6#168]
获取歌单列表中音乐名称的text集合，同一id
测试时没有切换任何界面，一直停留在歌单界面，依然报错

测试代码如下
```
console.show();
let count =0;
function main() {
    let music_name_list = pickup(id('second_line'), "$[]");
    music_name_list.length>0 && log(`运行${++count}次`)   
}
while (1) {
    main()
    sleep(333);   
}
```
运行了70次报错，有时候几百次不报错
报错信息如下
13:21:49.234/E: Wrapped java.lang.IllegalStateException: No bridges have been set (file:///android_asset/modules/__selector__.js#43)
Wrapped java.lang.IllegalStateException: No bridges have been set
    at file:///android_asset/modules/__selector__.js:43:0
    at main (/storage/emulated/0/脚本/我的代码/cs.js:4:0)
    at /storage/emulated/0/脚本/我的代码/cs.js:9:0

gpt回答
这是一个JavaScript脚本错误，具体错误信息为：在文件file:///android_asset/modules/selector.js的第43行发生了一个java.lang.IllegalStateException类型的错误，原因是没有设置桥接（bridges）

使用［$］和｛w｝获取控件集合，都会出现此报错
![Screenshot_20231106_132525](https://github.com/SuperMonster003/AutoJs6/assets/143495929/ec352a71-528c-4c80-9dc7-69bc420327f6)

**Comment by sucutey** [comment]
先前6.2版本没有出现此报错

**Comment by SuperMonster003** [comment]
感谢反馈, 下一版本将尝试修复上述问题.

_Sent from my XQ-DQ72 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
