### ISSUE TITLE
奇怪，安装最新版后，打开发现没有脚本文件夹了

### ISSUE THREAD

**Issue by lnxcyq** [SuperMonster003/AutoJs6#17]

**Comment by SuperMonster003** [comment]
如果是高版本安卓系统, 需要授予 "管理所有文件" 权限, 在启动 AutoJs6 时应该会主动弹窗提示, 否则需要手动授予.
另外如果之前旧版修改了默认脚本路径, 在新版 AutoJs6 需重新设置.
另外新版报名变更, 如果安装过旧版 AJ6, 会出现两个同名的 AutoJs6 应用, 需注意区分 (建议卸载旧版).

**Comment by SuperMonster003** [comment]
上述问题经测试后复现
测试机型: Android 10 (Q) [29]
将于后续版本尝试修复

**Comment by a4youma** [comment]
> 

测试：在小米 Android 9 上正常，在 Android 10 上不能显示脚本文件夹，也无法新建文件，存储权限给了也没有任何用处

**Comment by a4youma** [comment]
测试：华为鸿蒙2.0.0.233，与Android 10一样，不能显示脚本文件夹，都不能创建文件或文件夹。

**Comment by lnxcyq** [comment]
这个问题在AutoX.js的一次升级中也出现过，后来他们及时修改了，建议可以去参观一下他们是怎么修改过来的。

**Comment by SuperMonster003** [comment]
这个问题已经标记受理了, 将在下一版本修复, 请关注后续版本更新 (不晚于 May 31, 2022)
