### ISSUE TITLE
缺少org.autojs.autojs6包下面的文件 

### ISSUE THREAD

**Issue by thinkido** [SuperMonster003/AutoJs6#170]
代码中有引入这个包的类，但找不到对应文件。org.autojs.autojs6

**Comment by SuperMonster003** [comment]
请详述具体的问题, 在什么运行环境下, 执行怎样的代码, 具体报错是什么等等.

另外提供一个简单的示例, 在 AutoJs6 中执行以下代码可以获取到软件版本名称:

```js
console.log(org.autojs.autojs6.BuildConfig.VERSION_NAME);
```

**Comment by thinkido** [comment]
> 请详述具体的问题, 在什么运行环境下, 执行怎样的代码, 具体报错是什么等等.
> 
> 另外提供一个简单的示例, 在 AutoJs6 中执行以下代码可以获取到软件版本名称:
> 
> ```js
> console.log(org.autojs.autojs6.BuildConfig.VERSION_NAME);
> ```

不知道BuildConfig是自动生成的。而不是固定的类文件。
