### ISSUE TITLE
currentActivity()判断页面位置问题

### ISSUE THREAD

**Issue by HDJN** [SuperMonster003/AutoJs6#171]
## 问题描述
- currentActivity() 判断页面位置时，大部分情况能继续执行。有时候不准确，不能继续执行，把任务结束掉，重新执行，就没有问题。

## 代码如下
```js
let o = {};
o.method1 = function () {
    let flag = true;
    if (flag) {
        this.util();//卡在这里，没有往下执行
    }
    //...
    return this;
}
o.method2 = function () {
    //...
    return this;
}
o.util = function () {
    sleep(3000);
    if ("aaa" !== currentActivity()) { //卡在这里，其实这里已经进入了 aaa activity
        console.log("xxxxx"); //打印出内容
        return;
    }
    //...
}
o.method1().method2();
```

**Comment by sucutey** [comment]
你直接死循环log（currentActivity（））切换页面你就会发现当前activity是会卡住的，比如按一下音量键，然后当前的activity都是音量键跳出来的那个activity（android.app.xxx），还有某些界面也是会卡住的，靠这个判断界面还不如用xxx.untilFind（）

**Comment by HDJN** [comment]
> 你直接死循环log（currentActivity（））多切换几个页面，你就会发现当前activity是会卡住的，不会实时更新的 比如按一下音量键，然后当前的activity一直都是音量键的那个activity（android.app.xxx），还有某些界面也是会卡住的，靠这个判断界面还不如用xxx.untilFind（）实在

好的，我把这种方式去掉再试试

**Comment by SuperMonster003** [comment]
`currentActivity()` 隐含 `auto()`, 因此很可能是 `auto()` 方法导致了阻塞.
下一版本将尝试避免 `auto()` 引起的阻塞.
