### ISSUE TITLE
TypeError: text 是 string 而非函数

### ISSUE THREAD

**Issue by Xerzsh** [SuperMonster003/AutoJs6#173]
```
const date = new Date();
const hours = date.getHours();
const minutes = date.getMinutes();
const timeString = `${hours}:${minutes}`;
text(timeString).findOne().parent().click();
```
这令我困惑。timeString这个变量的类型不就是string吗？

**Comment by sucutey** [comment]
上面代码没错，错误不在这里

**Comment by Xerzsh** [comment]
> 上面代码没错，错误不在这里

![Screenshot_2023-11-13-18-58-56-021_org autojs autojs6](https://github.com/SuperMonster003/AutoJs6/assets/48620641/4cfd2e0c-4595-4a5b-9850-57dff9113881)
![微信图片_20231113191856](https://github.com/SuperMonster003/AutoJs6/assets/48620641/ec8a7f8b-ee1c-4fae-a4ba-54b858af7a07)

**Comment by Xerzsh** [comment]
> 上面代码没错，错误不在这里

解决了。因该是我在21行所声明的同名变量所致

**Comment by sucutey** [comment]
你把全局的text指向修改成字符串了，原本是text=function(){}
