### ISSUE TITLE
偶尔用着别的app，autojs6突然跳出来启动然后崩溃

### ISSUE THREAD

**Issue by hlyzhot** [SuperMonster003/AutoJs6#183]
以前偶尔出现，我也没定时任务，一直找不到原因，崩溃也没来得及复制。刚刚似乎发现了原因，可能跟使用 "音量加" 键控制脚本运行功能有关，我看视频调大音量时，autojs6又突然启动然后崩溃，这次我复制到了日志：
Version: 2180
Android: 31
java.util.concurrent.RejectedExecutionException: Task org.autojs.autojs.core.accessibility.AccessibilityService$$ExternalSyntheticLambda1@aaf8812 rejected from java.util.concurrent.ThreadPoolExecutor@81e9be3[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
org.autojs.autojs.core.accessibility.AccessibilityService.onKeyEvent(AccessibilityService.kt:81)
android.accessibilityservice.AccessibilityService$2.onKeyEvent(AccessibilityService.java:2195)
android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2434)
com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loopOnce(Looper.java:210)
android.os.Looper.loop(Looper.java:299)
android.app.ActivityThread.main(ActivityThread.java:8273)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by nsy9601** [comment]
我也遇到这样的情况，只要按下音量键，不管是音量加还是音量减，autojs6都会崩溃，在设置里把音量键的开关关闭也一样。

**Comment by RFSN** [comment]
这个问题很频繁，经常动不动崩溃，复制调试信息，也是这个错误，我出现在新建文件，或者编辑文件过程中。

**Comment by SuperMonster003** [comment]
感谢反馈, 将于下一版本尝试修复上述问题.

_Sent from my XQ-DQ72 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
