### ISSUE TITLE
希望打包后的脚本也可以使用 app.sendBroadcast("inspect_layout_bounds"); 方便调试

### ISSUE THREAD

**Issue by diuchouni** [SuperMonster003/AutoJs6#197]
name {string} 特定的广播名称，包括：
inspect_layout_hierarchy 布局层次分析
inspect_layout_bounds 布局范围
发送以上特定名称的广播可以触发Auto.js的布局分析，方便脚本调试。这些广播在Auto.js发送才有效，在打包的脚本上运行将没有任何效果。

app.sendBroadcast("inspect_layout_hierarchy");
或者 
app.sendBroadcast("inspect_layout_bounds");

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/AutoJs6/issues/95#issuecomment-1952523978

如上述 issue 所述, 可通过授予打包应用相关权限解决问题, 此 issue 暂时关闭, 如仍有问题, 可重新开启或发起新的 issue.
