### ISSUE TITLE
识别工整字体的 OCR 功能 (Edited)

### ISSUE THREAD

**Issue by keep-an** [SuperMonster003/AutoJs6#2]

**Comment by keep-an** [comment]
https://github.com/hamibot/hamibot在autojs基础上增加了OCR，可以参考把功能复制过来

**Comment by SuperMonster003** [comment]
能力有限, 无法添加. 当前项目开发者只是 Android 及 Java 初学者. 最多是在原有项目基础上做些能力之内的简单修改.

**Comment by SuperMonster003** [comment]
已于 [v6.3.0](https://github.com/SuperMonster003/AutoJs6/releases/tag/v6.3.0) 增加基于 Google MLKit 的简单 OCR 功能.  
试用后如有相关问题或建议, 可于此处反馈或提交新的 `议题 (Issue)` 反馈.
