### ISSUE TITLE
无法调用 console.setLogSize() 方法 (Edited)

### ISSUE THREAD

**Issue by lnxcyq** [SuperMonster003/AutoJs6#20]
console.show();
 console.setLogSize(10);这一行出错，必须把console.setLogSize(10);删掉才行

**Comment by SuperMonster003** [comment]
![image](https://user-images.githubusercontent.com/30370009/171517316-99467bc8-a071-48ab-8a63-3f1196bb66d7.png)

console 没有 setLogSize() 方法

**Comment by lnxcyq** [comment]
最近隔壁更新好快啊，咱这个就慢了点哦

**Comment by SuperMonster003** [comment]
`console.setLogSize` 可能源自其他 Auto.js 版本的封装方法.

AutoJs6 [v6.3.0](https://github.com/SuperMonster003/AutoJs6/releases/tag/v6.3.0) 增加了 `console.setContentTextSize` 方法用于设置控制台浮动窗口日志区域的文本字号, 使用方式详见 [应用文档 > 控制台 (Console)](https://docs.autojs6.com/#/console) 章节.
