### ISSUE TITLE
6.5.0版本打包后app 启动闪退

### ISSUE THREAD

**Issue by wgq4812** [SuperMonster003/AutoJs6#202]
没事了。打扰了。

**Comment by wgq4812** [comment]
代码在 autojs6 里  运行无问题，打包后的APP运行直接闪退。

**Comment by SuperMonster003** [comment]
关键日志条目:
```text
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjackpal-termexec2.so" not found
```
上述问题与 #223 相似, 将于下一版本尝试修复.

另, Shizuku 无法在打包应用中正常使用, 与 #227 及 #231 类似, 将于后续版本尝试修复.

**Comment by Vdaoren** [comment]
目前手动添加再打包即可

**Comment by gengkf** [comment]
这个问题修复了吗。

**Comment by HiColinMe** [comment]
6.7.0,
`java.lang.UnsatisfiedLinkError: dlopen failed: library "libjackpal-termexec2.so" not found`
这个问题依然存在,打包后崩溃,调试期间正常
