### ISSUE TITLE
请问AutoJs6与AutoJsX的区别是什么？有什么不一样的功能？

### ISSUE THREAD

**Issue by ListenV** [SuperMonster003/AutoJs6#216]
或者换一种说法为什么要再建立一个相同的项目？

我看了文档和ReadMe，并没有类似的QA

作为一个新手，我感到迷惑，我觉得应该将这些写进文档，方便新手入门，也能帮助我们招揽更多用户

另外，这个项目很棒！

**Comment by wingswing1** [comment]
两者差不多吧，autox更新快点但是bug也多，提出bug也没人解决。这边更新慢，主要是oom问题比较头疼，两边都试试，看看哪个适合你

**Comment by ListenV** [comment]
好的，感谢

**Comment by SuperMonster003** [comment]
两个项目都是基于 Auto.js 4.1.1 alpha2 进行二次开发的.

项目的每次迭代都有详细的 `更新记录 (Changelog)`:
- [AutoX 更新记录](https://github.com/kkevsekk1/AutoX/blob/dev-test/CHANGELOG.md)
- [AutoJs6 更新记录](http://changelog.autojs6.com/)

项目创建时间, AutoX 早于 AutoJs6:
- AutoX: 2020/07/24
- AutoJs6: 2021/12/01

之所以创建 AutoJs6, 是希望通过这个项目, 学习 Java 和 Android, 并希望在有余力的前提下, 边学习, 边对 Auto.js 进行一些完善, 让 Auto.js 能延续它的价值, 也让更多的开发者受益.

**Comment by SuperMonster003** [comment]
两个项目都是基于 Auto.js 4.1.1 alpha2 进行二次开发的.

项目的每次迭代都有详细的 `更新记录 (Changelog)`:
- [AutoX 更新记录](https://github.com/kkevsekk1/AutoX/blob/dev-test/CHANGELOG.md)
- [AutoJs6 更新记录](http://changelog.autojs6.com/)

项目创建时间, AutoX 早于 AutoJs6:
- AutoX: 2020/07/24
- AutoJs6: 2021/12/01

之所以创建 AutoJs6, 是希望通过这个项目, 学习 Java 和 Android, 并希望在有余力的前提下, 边学习, 边对 Auto.js 进行一些完善, 让 Auto.js 能延续它的价值, 也让更多的开发者和使用者受益.
