### ISSUE TITLE
UiObject#compass - 控件罗盘

### ISSUE THREAD

**Issue by SuperMonster003** [SuperMonster003/AutoJs6#23]
用于传递给 [控件罗盘](https://docs.autojs6.com/#/uiObjectType?id=m-compass) 的参数类型, 又称 罗盘参数.

罗盘参数是字符串类型, 支持单独或组合使用.

参阅 [应用文档 > 数据类型 (Data Types) > DetectCompass](https://docs.autojs6.com/#/dataTypes?id=detectcompass)

**Comment by a4youma** [comment]
非常期待，希望尽快发布~~~
