### ISSUE TITLE
PaddleOCR支持

### ISSUE THREAD

**Issue by TonyJiangWJ** [SuperMonster003/AutoJs6#24]
要不要来个PaddleOCR的支持，我最近搞的已经可以支持PaddleOCR V3了 可以的话我周末提一个PR到你的项目

**Comment by SuperMonster003** [comment]
欢迎至极 😄

**Comment by TonyJiangWJ** [comment]
搞定了

**Comment by SuperMonster003** [comment]
谢谢 Tony

**Comment by lnxcyq** [comment]
怎么还没更新啊，期盼中

**Comment by nsy9601** [comment]
急需ocr,同样期盼尽快更新

**Comment by xm0625** [comment]
https://github.com/xm0625/paddleOcrPlugin

PaddleOCR 百度超轻量级OCR模型 速度快 准确率高于Google ML Kit
记得star

**Comment by SuperMonster003** [comment]
目前 Paddle 已完成整合, 感谢 Tony.
❤️
