### ISSUE TITLE
半年过去了，作者还不修修bug啊，打包打不了很难受

### ISSUE THREAD

**Issue by jinjinv587** [SuperMonster003/AutoJs6#249]
半年过去了，作者还不修修bug啊，打包打不了很难受啊

**Comment by qqxiaoteng** [comment]
可以看源码自己修，懂Java后是比较简单的

**Comment by wingswing1** [comment]
是呀，隔壁不停地更新

**Comment by qqxiaoteng** [comment]
隔壁是哪个项目，发一下看看。

**Comment by wingswing1** [comment]
autox



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月17日 17:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [SuperMonster003/AutoJs6] 半年过去了，作者还不修修bug啊，打包打不了很难受 (Issue #249) |

隔壁是哪个项目，发一下看看。

**Comment by jinjinv587** [comment]
那个bug一堆，更难用，最新版都没法用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wingswing1 ***@***.***&gt;
发送时间: 2024年7月17日 18:05
收件人: SuperMonster003/AutoJs6 ***@***.***&gt;
抄送: jinjinv587 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [SuperMonster003/AutoJs6] 半年过去了，作者还不修修bug啊，打包打不了很难受 (Issue #249)





 autox
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2024年07月17日 17:57 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;***@***.***&gt; |
 | 主题 | Re: [SuperMonster003/AutoJs6] 半年过去了，作者还不修修bug啊，打包打不了很难受 (Issue #249) |
 
 隔壁是哪个项目，发一下看看。

**Comment by lanmingle** [comment]
我一直用隔壁 6.4.3 这个版本，后面的版本各种各样的问题

https://github.com/lanaqi-opensource/autox-typescript-template
