### ISSUE TITLE
ocr.detect输出的是javaObject

### ISSUE THREAD

**Issue by MaGc9311** [SuperMonster003/AutoJs6#274]

**Comment by SuperMonster003** [comment]
是的, 6.6.0 将很多原本是 JavaScript Object 的值转换为了 Java 对象.

我不知道你具体的期望是什么, 或者说 JavaObject 给你带来了哪些不便.

如果是希望在打印 oct.detect() 结果时可以快速获取每一个结果的摘要, 可暂时通过以下代码实现:

```js
console.log(ocr.detect().map(o => o.toString()));
```

否则, 请简述你的具体需求.

**Comment by MaGc9311** [comment]
> 是的, 6.6.0 将很多原本是 JavaScript Object 的值转换为了 Java 对象.
> 
> 我不知道你具体的期望是什么, 或者说 JavaObject 给你带来了哪些不便.
> 
> 如果是希望在打印 oct.detect() 结果时可以快速获取每一个结果的摘要, 可暂时通过以下代码实现:
> 
> ```js
> console.log(ocr.detect().map(o => o.toString()));
> ```
> 
> 否则, 请简述你的具体需求.

谢谢！有那段代码就可以了
