### ISSUE TITLE
打包插件是不能下载的吗？

### ISSUE THREAD

**Issue by diuchouni** [SuperMonster003/AutoJs6#28]
![QQ截图20220731144403](https://user-images.githubusercontent.com/97949901/182013687-c74731ab-1c1b-4fa4-b62f-e35d28ca0da8.jpg)

**Comment by SuperMonster003** [comment]
打包插件目前托管在 GitHub 网站上, 请检查设备网络是否可以正常访问上述网站, 必要时可能需要代理网络
