### ISSUE TITLE
JavaScript 模块名覆盖声明时存在隐患

### ISSUE THREAD

**Issue by SuperMonster003** [SuperMonster003/AutoJs6#29]
JavaScript 模块名被覆盖声明时,
将导致存在依赖关系的内部模块无法正常使用.

例如 console 模块依赖了 util 模块,
util 覆盖声明时将导致 console 无法使用:

```js
console.log("hello"); // 正常
```

```js
let util = null;
console.log("hello"); // 报错
```

**Comment by a4youma** [comment]
快半年每升级了，非常期待能尽快升级到6.2.1版

**Comment by SuperMonster003** [comment]
@a4youma 
目前下一版本还在内测中, 如有兴趣可加入体验.
![hTtpW3j](https://user-images.githubusercontent.com/30370009/196013973-da65edc9-4b9e-40ea-97b2-4b0079469915.png)
