### ISSUE TITLE
希望能支持一下 websocket

### ISSUE THREAD

**Issue by getda** [SuperMonster003/AutoJs6#36]

**Comment by SuperMonster003** [comment]
将在后续版本实现 ws 模块的封装.

**Comment by dqss** [comment]
希望能支持wss链接，携带证书，或者忽略证书，https也一样，麻烦了

**Comment by SuperMonster003** [comment]
@dqss 
将于 v6.3.1 支持简单的 WebSocket 常规方法, 证书相关方法将于后续版本实现.  
如果可以的话, 建议提供与证书相关的 [ 示例代码 / 伪代码 / 详细需求 ] 等, 以便于后续 API 的针对性封装.

**Comment by dqss** [comment]
> @dqss 将于 v6.3.1 支持简单的 WebSocket 常规方法, 证书相关方法将于后续版本实现. 如果可以的话, 建议提供与证书相关的 [ 示例代码 / 伪代码 / 详细需求 ] 等, 以便于后续 API 的针对性封装.

我有代码，但是需要导入dex支持，方便私聊吗

**Comment by SuperMonster003** [comment]
可加入项目的腾讯内测群组.  
AutoJs6 设置页面, 长按 "应用与开发者" 按钮, 点击 "加入群组".

**Comment by SuperMonster003** [comment]
v6.3.1 已支持简单的 WebSocket 常规方法.
