### ISSUE TITLE
canvas绘制线段时，颜色无法正常已设置的色值展示，显示的白色；代码如下

### ISSUE THREAD

**Issue by Garryzhang** [SuperMonster003/AutoJs6#38]
var paintLine = new android.graphics.Paint();
paintLine.setAntiAlias(true); //抗锯齿
paintLine.setAlpha(255); //0~255透明度
paintLine.setFakeBoldText(true);
paintLine.setStrokeWidth(2);
paintLine.setStyle(android.graphics.Paint.Style.STROKE);
paintLine.setColor(colors.parseColor("#FF963200"));

console.log("#FF963200的整数值为：", colors.parseColor("#FF963200"));
var color = paintLine.getColor();
console.log("线的颜色：", color);

控制输出的结果为：

14:55:04.596/D: #FF963200的整数值为： -6934016
14:55:04.597/D: 线的颜色： -1

**Comment by SuperMonster003** [comment]
尝试修改代码如下:

```js
var paintLine = new android.graphics.Paint();
paintLine.setAntiAlias(true); //抗锯齿
paintLine.setAlpha(255); //0~255透明度
paintLine.setFakeBoldText(true);
paintLine.setStrokeWidth(2);
paintLine.setStyle(android.graphics.Paint.Style.STROKE);

// paintLine.setColor(colors.parseColor("#FF963200"));
colors.setPaintColor(paintLine, '#963200');

console.log("#FF963200的整数值为：", colors.parseColor("#FF963200"));
var color = paintLine.getColor();
console.log("线的颜色：", color);
```

上述代码使用了 colors 模块的封装方法 setPaintColor(paint, color).

我把文档复制过来, 里面解释了不能正常设置颜色的原因.

---

## [m] setPaintColor

### setPaintColor(paint, color)

- **paint** { [android.graphics.Paint](https://developer.android.com/reference/android/graphics/Paint) } - 画笔参数
- **color** { [ColorHex](https://supermonster003.github.io/AutoJs6-Documentation/#/dataTypes?id=colorhex) | [ColorInt](https://supermonster003.github.io/AutoJs6-Documentation/#/dataTypes?id=colorint) | [ColorName](https://supermonster003.github.io/AutoJs6-Documentation/#/dataTypes?id=colorname) } - 颜色参数
- <ins>**returns**</ins> { [void](https://supermonster003.github.io/AutoJs6-Documentation/#/dataTypes?id=void) }

方法 `setPaintColor` 用于解决在 `Android API 29 (10) [Q]` 及以上系统中 `Paint#setColor(color)` 无法正常设置画笔颜色的问题.

```js
let paint = new android.graphics.Paint();

/* 安卓 10 及以上系统无法正常设置颜色. */
// paint.setColor(colors.toInt('blue'));

/* 使用 colors 模块实现原始功能. */
colors.setPaintColor(paint, 'blue');
```

画笔无法正常设置颜色的原因, 是 `Android API 29 (10) [Q]` 源码中 `setColor` 有以下两种方法签名:

```text
setColor(@ColorInt int color): void
setColor(@ColorLong long color): void
```

JavaScript 语言不区分 `int` 和 `long`, 即只有 `setColor(color: number)`,  
它会优先匹配 Java 的 `setColor(@ColorLong long color): void`.

`ColorLong` 颜色与 `ColorInt` 颜色不同在于, 前者包含了额外的 `ColorSpace` (颜色空间) 信息,  
原有的 `ColorInt` 被当做 `ColorLong` 来解析, 导致颜色解析异常.

除上述 `colors.setPaintColor` 的方法外, 还有其他一些解决方案:

```js
/* A. 使用 paint.setArgb 方法. */
paint.setARGB(
    colors.alpha(color),
    colors.red(color),
    colors.green(color),
    colors.blue(color),
);

/* 同上, 语法更简洁. */
paint.setARGB.apply(paint, colors.toArgb(color));

/* B. 将 ColorInt "打包" 为 ColorLong. */
paint.setColor(android.graphics.Color.pack(colors.toInt(color)));

/* C. 直接使用带 ColorSpace 信息的 ColorLong. */
paint.setColor(android.graphics.Color.pack(
    colors.redDouble(color),
    colors.greenDouble(color),
    colors.blueDouble(color),
    colors.alphaDouble(color),
    android.graphics.ColorSpace.get(android.graphics.ColorSpace.Named.SRGB),
));
```

`colors.setPaintColor` 的大致源码:

```js
function setPaintColor(paint, color) {
    if (util.version.sdkInt >= util.versionCodes.Q) {
        paint.setARGB.apply(paint, colors.toArgb(color));
    } else {
        paint.setColor(colors.toInt(color));
    }
}
```
