### ISSUE TITLE
v6.0.1版在Android 7模拟器中无法使用ui

### ISSUE THREAD

**Issue by perida** [SuperMonster003/AutoJs6#4]
v6.0.0没有出现下面的问题。

使用市面常见的最新版本的雷电、逍遥模拟器（都是Android 7.1），如运行Autojs6中 示例代码 - 本地存储 - 随手记，会出现错误：
/E: Wrapped android.view.InflateException: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup (file:///android_asset/modules/__ui__.js#18)
Wrapped android.view.InflateException: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
    at file:///android_asset/modules/__ui__.js:18:0
    at /data/user/0/org.autojs.autojs/files/sample/本地存储/随手记.js:2:0

**Comment by SuperMonster003** [comment]
当前项目只能运行在 android 8 及以上系统.
