### ISSUE TITLE
Auto.js-ApkBuilder这个库没权限了啊

### ISSUE THREAD

**Issue by hacklx** [SuperMonster003/AutoJs6#40]
> Could not resolve com.github.hyb1996:Auto.js-ApkBuilder:1.0.3.
         > Could not get resource 'https://jitpack.io/com/github/hyb1996/Auto.js-ApkBuilder/1.0.3/Auto.js-ApkBuilder-1.0.3.pom'.
            > Could not GET 'https://jitpack.io/com/github/hyb1996/Auto.js-ApkBuilder/1.0.3/Auto.js-ApkBuilder-1.0.3.pom'. Received status code 401 from server: Unauthorized

**Comment by GiGaFotress** [comment]
你都看到是hyb1996的库了不知道他跑路了么

**Comment by 18739087660** [comment]
我也有同样的问题

**Comment by anxiazifeng** [comment]
找源码自己编译吧

**Comment by SuperMonster003** [comment]
参阅 #44
