### ISSUE TITLE
请支持Tasker插件

### ISSUE THREAD

**Issue by baskgithub** [SuperMonster003/AutoJs6#41]
Autojs一直是支持tasker的。
可是autojs6却好像不行了？
tasker选择插件，如图，
![Screenshot_2023-03-21-22-35-11-283_net dinglisch android taskerm](https://user-images.githubusercontent.com/24505459/226639823-66684689-dc0f-4b80-813d-bb183df63d9a.jpg)
并不能进去脚本选择界面, autojs是可以的。

**Comment by SuperMonster003** [comment]
已于 [v6.3.0](https://github.com/SuperMonster003/AutoJs6/releases/tag/v6.3.0) 尝试修复上述问题.

如问题复现, 可继续反馈.

**Comment by baskgithub** [comment]
v6.3.0 
works well with tasker 🤝 支持tasker插件

😁😃😄
