### ISSUE TITLE
VSCode使用AutoJS6新建项目，得到一个空的？

### ISSUE THREAD

**Issue by onlyWYY** [SuperMonster003/AutoJs6#42]
![image](https://user-images.githubusercontent.com/15945604/230338483-37eeb978-9c1c-4331-ae74-ade810154f15.png)
创建完成，没有main.js，也没有project.json文件，不知道哪里操作错了？

**Comment by SuperMonster003** [comment]
插件的项目相关功能存在问题 暂无法正常使用 请等待后续版本更新
