### ISSUE TITLE
toast 在其余界面无效

### ISSUE THREAD

**Issue by sishentibu** [SuperMonster003/AutoJs6#43]
代码：
`sleep(3000);
toast("good");
`
手机 mate 20 pro 鸿蒙os 3
运行后，在autojs 软件界面，有提示。
在其余界面，如 桌面，中国银行 等，没有显示。
换用 toastLog 同样不行。
重启手机也不行。

请问是否还需要增加别的代码？

**Comment by ZzzMiles** [comment]
你必须授予Autojs6通知权限。两秒之内的两个toast，后面那个不显示。

**Comment by sishentibu** [comment]
> 你必须授予Autojs6通知权限。两秒之内的两个toast，后面那个不显示。

通知权限已经给了的。
但是根据你的提示，仔细看了下各种权限，发现有个“后台弹窗”的权限，开了后就可以了。
