### ISSUE TITLE
我在将您的项目导入Android studio的过程中总是出错，能否分享一下您的相关配置？

### ISSUE THREAD

**Issue by SongYeXiaoLuo** [SuperMonster003/AutoJs6#44]
具体是无法调试应用，也无法签名，签名的过程总是跳转到第一开发者的github上
显示https://jitpack.io/com/github/hyb1996/Auto.js-ApkBuilder/1.0.3/Auto.js-ApkBuilder-1.0.3.pom

**Comment by SuperMonster003** [comment]
已于 [v6.3.0](https://github.com/SuperMonster003/AutoJs6/releases/tag/v6.3.0) 尝试将上述依赖库本地化.

如问题复现, 可继续反馈.
