### ISSUE TITLE
在布局层次中查看的问题

### ISSUE THREAD

**Issue by dqss** [SuperMonster003/AutoJs6#46]
如果太多层的话整个页面都让层次占满了，看不到后面的信息，完全没法用，是否可以取消前面的层次排序，只保留展开按钮，这样也是可以分析层次的。
![在布局层次中查看](https://user-images.githubusercontent.com/50577191/231562947-36e93ddf-0ac9-4b80-9f68-4b2ad4e6b52b.png)

**Comment by SuperMonster003** [comment]
后续版本将针对上述极端情况做出优化, 但开发周期可能较长, 请关注后续版本更新.

**Comment by SuperMonster003** [comment]
v6.3.1 已尝试改善上述问题, 如依然影响使用, 可继续反馈.
