### ISSUE TITLE
[TypeError: 对象 floaty 不存在方法 checkPermission.

### ISSUE THREAD

**Issue by dqss** [SuperMonster003/AutoJs6#47]

**Comment by SuperMonster003** [comment]
`floaty.checkPermission` 可能源自其他 Auto.js 版本的封装方法.

AutoJs6 [v6.3.0](https://github.com/SuperMonster003/AutoJs6/releases/tag/v6.3.0) 增加了 `floaty.hasPermission` / `floaty.requestPermission` 方法用于获取 "显示在其他应用上层" 权限授予状态及权限请求.

**Comment by hduwhyso** [comment]
为啥不和原作者一样啊，用floaty.requestPermission。这样软件适配会好点

**Comment by SuperMonster003** [comment]
@hduwhyso `floaty.requestPermission` 已经可用.

**Comment by hduwhyso** [comment]
> @hduwhyso `floaty.requestPermission` 已经可用.

6.4.1还是提示不存在方法checkPermission。floaty.checkPermission()这个命令用不了

**Comment by hduwhyso** [comment]
目前AJ6的方法是floaty.hasPermission()；能不能和原版一样，也用floaty.checkPermission()这个方法。

**Comment by SuperMonster003** [comment]
@hduwhyso 

AutoJs6 将继续保持 `floaty.hasPermission` 方法用于检查权限, 未来 `checkPermission` 将返回权限状态常量值.

按照 Android 的多数方法签名规律, 总结权限相关的方法如下.

- checkPermission / checkSelfPermission

    - 用于检查权限, 返回权限的状态常量值, 如 `android.content.pm.PackageManager.PERMISSION_DENIED` 和 `android.content.pm.PackageManager.PERMISSION_GRANTED` 等.

- hasPermission

    - 用于判断是否被授予权限, 使用的一般是 `checkPermission() == android.content.pm.PackageManager.PERMISSION_GRANTED` 判断方法.

另外还有几个 AutoJs6 常用的权限相关的方法

- requestPermission

    - 申请权限.

- revokePermission

    - 撤销权限.

- ensurePermission

    - 确保权限授予, 否则将抛出异常.

AutoJs6 将尽量保证与 Auto.js 4.x 保持 API 的一致, 但为了更贴近方法名称的语义, checkPermission 将与原有 API 存在出入.

如果需要兼容其他版本 Auto.js, 可使用类似以下条件语句:

```js
let hasFloatyPermission = context.packageName.includes('autojs6')
    ? floaty.hasPermission()
    : floaty.checkPermission();
console.log(hasFloatyPermission);
```
