### ISSUE TITLE
boundsInside(0, 0, -1, -1)筛选无效

### ISSUE THREAD

**Issue by ChrisCatCP** [SuperMonster003/AutoJs6#49]
在使用boundsInside(0, 0, -1, -1)筛选屏幕内的控件是  (93,247 - 1023,-1127)  这种bottom为负数的控件无法排除 
使用boundsInside(0, 0, device.width , device.height) 也是一样

**Comment by ChrisCatCP** [comment]
```js
filter((w)=>{
    let bounds = w.bounds();
    let left = Math.min(bounds.left,bounds.right);
    let right = Math.max(bounds.left,bounds.right);
    let top = Math.min(bounds.top,bounds.bottom);
    let bottom = Math.max(bounds.top,bounds.bottom);
    let screen = new android.graphics.Rect(0,0,device.width,device.height);
    return screen.contains(new android.graphics.Rect(left,top,right,bottom));
  })
```
这样解决了 但是如果能添加到源码就好了  
我这边无法正常编译  apkbuilder那个库没有权限

**Comment by SuperMonster003** [comment]
已于 [v6.3.0](https://github.com/SuperMonster003/AutoJs6/releases/tag/v6.3.0) 尝试修复上述问题.  
包括 [ 边界倒置控件矩形筛选 / ApkBuilder 依赖无法访问 ].  
如问题复现, 可继续反馈.

另外你提供的 filter 解决思路是可行的, 你也可以参考 AutoJs6 v6.3.0 的解决方法:  
https://github.com/SuperMonster003/AutoJs6/blob/6ff598d587d37d672d3e21c807694b600f92c6c8/app/src/main/java/org/autojs/autojs/core/automator/filter/BoundsFilter.kt

**Comment by ChrisCatCP** [comment]
新版对于倒置控件能正确筛选了
