### ISSUE TITLE
这个AutoJs6如何生成APK文件，在手机上运行呢？

### ISSUE THREAD

**Issue by minirain2000** [SuperMonster003/AutoJs6#5]
该源码如何打包成APK文件啊？？？'

**Comment by SuperMonster003** [comment]
项目的 release 有打包好的 apk 文件.
如需自行编译打包, 需使用 Android Studio.

**Comment by minirain2000** [comment]
> 项目的 release 有打包好的 apk 文件. 如需自行编译打包, 需使用 Android Studio.
> […](#)
> On January 14, 2022 20:11:43 minirain2000 ***@***.***> wrote: 该源码如何打包成APK文件啊？？？' — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
我自己编译了一下【因为项目 release下是空文件，仅有一个文件：output.json】，编译时提示下列错误：
> Task :common:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:compileDebugJavaWithJavac'.
> 错误: 无效的源发行版：16

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by minirain2000** [comment]
![1642284357(1)](https://user-images.githubusercontent.com/12096661/149639164-05dd66b3-8aeb-415b-8800-4aa8f91e578d.png)

**Comment by SuperMonster003** [comment]
首先准备好 [Java Development Kit (JDK) 16](https://www.oracle.com/java/technologies/javase/jdk16-archive-downloads.html) 开发工具包
并记录已安装的工具包所在目录 (简称 SDK 目录)
如 `D:\Program Files\Java\jdk16.0.2`

使用 [Android Studio Bumblebee 版本](https://developer.android.com/studio/preview) 打开项目

![image](https://user-images.githubusercontent.com/30370009/149688405-fc68d360-2f3c-4c5c-91f0-c6757ab60836.png)

注: Android Studio 正式版 及 Chipmunk 版 可能均无法正常编译项目

按下图提示完成 Android Studio 对 SDK 目录的定位

![image](https://user-images.githubusercontent.com/30370009/149688662-1dfe9fe2-6d6d-4072-a7d2-6bcadfd658d1.png)
![image](https://user-images.githubusercontent.com/30370009/149688763-fc8e390c-fde8-4dfc-b398-8c0f2ae3ac3c.png)
![image](https://user-images.githubusercontent.com/30370009/149688815-5aec2412-1578-4dd0-8b72-0e95cc16050a.png)

SDK 目录定位完成后 尝试重新编译项目

**Comment by minirain2000** [comment]
感谢你的细心回复。APK包打成了，在华为Mate30安装成功后，出现Autox.js界面后直按闪退是咋回事啊？

**Comment by minirain2000** [comment]
直接闪退。
