### ISSUE TITLE
console.setSize 无效

### ISSUE THREAD

**Issue by ChrisCatCP** [SuperMonster003/AutoJs6#50]
使用的时候有时候生效 有时候不生效 ...

**Comment by ChrisCatCP** [comment]
并且在使用悬浮窗时
```js
let window = floaty.window(
  <frame>
    <button id="action" text="search" w="90" h="40" bg="#77ffffff" />
  </frame>
);
console.show();
window.setPosition(
  device.width - button.getWidth(),
  device.height - button.getHeight() * 2
);
```

如果这里的console.show()  在 window.setPosition的下方  floaty就无法显示出来

**Comment by SuperMonster003** [comment]
console.setSize 问题已于 [v6.3.0](https://github.com/SuperMonster003/AutoJs6/releases/tag/v6.3.0) 尝试修复.  
如问题复现, 可继续反馈.

**Comment by ChrisCatCP** [comment]
@SuperMonster003 上版本遇到的控制台的显示问题基本都解决了  但是控制台现在变成单例了 
有两个问题  脚本初次调用show控制台会显示脚本运行开始等日志以及之前脚本的日志
并且之前脚本设置过大小坐标等 也会影响其他脚本

**Comment by SuperMonster003** [comment]
没错, console 浮动窗口现在是全局单例, 这样设计是因为希望 console 的 浮动窗口与 Activity 活动窗口实现信息同步

如果希望浮动窗口显示时重置之前的样式 可使用 console.reset 方法, 相见应用文档的 console 章节

**Comment by ChrisCatCP** [comment]
好吧  了解了
