### ISSUE TITLE
安卓13上没有通知权限

### ISSUE THREAD

**Issue by him007** [SuperMonster003/AutoJs6#55]
手机：红米K40 安卓13 MIUI14
autojs6版本：6.3.0
其它的权限都授予了，但是通知管理里面的允许通知无法点击，导致toast只能在autojs上弹出，在其它应用上无效，打开前台服务或者notice('hello');都没有通知。
用LibChecker查看一下，发现target api是33，推测是安卓13上高版本API的问题，找到了这个文档 https://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650268993&idx=1&sn=d7f4a53c0bd8c44405463d6296f3c297&chksm=8863142ebf149d38db6d53e77cf692c991842e7c2e9cc7cc664d29399cc8a95c20ff99a6c3f0&scene=27  。看了一下用apktool在AndroidManifest.xml中添加 `<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>` 声明权限，重新打包安装后通知管理里面可以允许通知了，不过只能打开autojs6文档。还需要修改下代码，不过我不懂安卓开发，不知道怎么修改。
可以的话麻烦开发者修复这个问题后发个测试版我测试一下。
![Screenshot_2023-05-04-05-23-55-255_com android settings-edit](https://user-images.githubusercontent.com/3102365/236053360-af2a1613-5a11-4f82-b197-429e1ed45bfc.jpg)

**Comment by SuperMonster003** [comment]
感谢反馈, 将于下一版本尝试修复上述问题.  
新版本发布后, 第一次运行是会弹出是否允许通知的对话框 (仅安卓 13+), 便于用于直接开启 "发布通知权限".  
即使用户点击 "不允许" 或点击对话框外部等方式关闭了对话框, 依然可以通过主页抽屉开启上述权限.

**Comment by SuperMonster003** [comment]
v6.3.1 已尝试修复上述问题, 如问题复现, 可继续反馈.  
另上述权限开关位于应用主页的侧拉抽屉中, 简体中文名称为 "发布通知权限".

**Comment by him007** [comment]
新版本正常了

**Comment by tanxinzheng** [comment]
@him007 兄弟，你的Android13是可以使用无障碍服务吗？
