### ISSUE TITLE
悬浮窗不能拖动，调节尺寸

### ISSUE THREAD

**Issue by asktaoing** [SuperMonster003/AutoJs6#60]
发现不能调节悬浮窗的尺寸和拖动
![IMG_20230507_194927](https://user-images.githubusercontent.com/32415644/236675840-9079f525-afbb-4cc2-a731-2ac5f1d54f0d.jpg)
下面的这个是AutoJs的相同的示例，都可以正常调节尺寸拖动
![IMG_20230507_195257](https://user-images.githubusercontent.com/32415644/236675846-7b7b96cd-c2b0-4f18-9361-e14bdf7038b0.jpg)
希望大佬能修复此BUG，十分感谢

**Comment by SuperMonster003** [comment]
感谢反馈 将于下一版本尝试修复上述问题 请关注后续版本更新

**Comment by SuperMonster003** [comment]
v6.3.1 已尝试修复上述问题, 如问题复现, 可继续反馈.
