### ISSUE TITLE
安卓 7.x 无法运行任何脚本

### ISSUE THREAD

**Issue by SuperMonster003** [SuperMonster003/AutoJs6#61]
![image](https://user-images.githubusercontent.com/30370009/236677107-794196c8-5610-4372-ae01-9b02e6859fd8.png)

因为 notice 模块源码中, 下述语句在使用 JavaScript 方式执行时, 因访问 `androidx.core.app.NotificationManagerCompat` 内部的 `android.app.NotificationChannel` 而导致 `ClassNotFoundException`.

```js
const NotificationManagerCompat = androidx.core.app.NotificationManagerCompat;
```

解决方案是将 `NotificationManagerCompat` 放置于 Android API 判断语句内部:

```js
if (util.version.sdkInt >= util.versionCodes.O) {
    androidx.core.app.NotificationManagerCompat.from(context).cancel(niceId);
}
```

**Comment by hellcoldby** [comment]
还是不行

**Comment by SuperMonster003** [comment]
@hellcoldby v6.3.1 已尝试修复上述问题, 如问题复现, 可继续反馈或开启新议题反馈, 当前议题暂时关闭.
