### ISSUE TITLE
希望支持vscode的断点和单步调试，对业余爱好者很有价值

### ISSUE THREAD

**Issue by YoungRadium** [SuperMonster003/AutoJs6#62]
对普通爱好者来说，编程就像魔法一样，神奇又吸引。但是因为没时间没精力没资源系统地学习，在探索的时候会遇到很多问题。如果能在运行的时候能够随时暂停，查看整个系统的状态，就非常有帮助作用了，就比如Excel的VBA，可以帮助做很多事情，虽然专业人士看起来可能有点简陋，但是对我们普通人来说就像外星武器一样。

所以希望AutoJS6也能增加这个功能。

**Comment by SuperMonster003** [comment]
上述功能超出个人能力范围, 此议题将标记为 "无法完成".

PS: 我也希望未来能有开发者实现 (或帮助实现) 上述功能.
