### ISSUE TITLE
安卓13 查找控件界面无法退出

### ISSUE THREAD

**Issue by sishentibu** [SuperMonster003/AutoJs6#63]
系统 ：vivo x90 (andriod 13).
autojs最新版，
复现使用的软件：起点（版本7.9.258）

复现操作：
打开起点，进入  我-福利中心 ， 然后使用 autojs 的悬浮窗查看控件信息（点击  看第x个视频---显示控件信息）。这时会弹出控件信息。
如果此时直接返回桌面（安卓手机直接从底部上划），则无法退出 查看控件信息  的模式。不管点哪，都是查看控件信息的操作。只能重启手机恢复。
在这种情况下，手机自带的 返回 操作（手机侧边往里滑动）失效。试过投屏到电脑上，利用电脑可以发送 返回 指令，退出 查看 控件信息的模式。

补充一下，可能是桌面的问题。发现如果是在安卓桌面启动 查看控件信息 功能，就会无法退出此功能。

**Comment by dqss** [comment]
试下锁屏再开我再安卓11出现类似的问题

**Comment by SuperMonster003** [comment]
v6.3.1 在布局分析浮动窗口菜单中加入了 "退出" 选项, 可用于关闭浮动窗口.  
如问题依然无法解决, 可在此继续反馈.

**Comment by sishentibu** [comment]
> 试下锁屏再开我再安卓11出现类似的问题

试过了，不起作用

**Comment by sishentibu** [comment]
> 

虽然操作上不太方便，但已经可以退出了。

**Comment by sishentibu** [comment]
> v6.3.1 在布局分析浮动窗口菜单中加入了 "退出" 选项, 可用于关闭浮动窗口. 如问题依然无法解决, 可在此继续反馈.

虽然操作上不太方便，但已经可以退出了。
