### ISSUE TITLE
可否永久开启服务端模式，不要自动关闭

### ISSUE THREAD

**Issue by dqss** [SuperMonster003/AutoJs6#64]
经常出现异常，无论电脑还是手机端退出都得重新打开服务，可否设置永久开启服务端模式，不要自动关闭

**Comment by SuperMonster003** [comment]
v6.3.1 已支持客户端模式非正常断开的自动连接, 以及服务端模式非正常断开后的自动开启.  
如有后续问题, 可继续于此处反馈.

**Comment by friend8179** [comment]
为什么我下载的最新版本打开左侧菜单都没有服务器模式选项  ?

**Comment by dqss** [comment]
还是会被关闭，例如打开了科学上网就会被关闭，切来切去的比较麻烦，可否打开后就不关，只能通过手动去关闭，毕竟可以打开这个开关的也没有自动关闭的需求呀

**Comment by SuperMonster003** [comment]
自 v6.3.2 起, AutoJs6 进一步优化了服务端模式的开关自动处理情况, 多数情况下服务端模式会保持开启 (即使断开已经建立的连接), 但 ke(1) xue(2) 上网导致网络条件变化 (IP 地址重新分配), 由此造成的连接断开无法避免. 一个可能可行的方案是针对 AutoJs6 设置 ke(1) xue(2) 上网软件的路由配置 (如添加到某个白名单, 使 AutoJs6 强制不走代理).
