### ISSUE TITLE
希望提供TS工程化项目

### ISSUE THREAD

**Issue by lanmingle** [SuperMonster003/AutoJs6#66]
弄了一个 autoxjs 的 ts 模板，想迁移到 autojs6 ，就是 autojs6 vscode 插件没有外部 API 可用，能否提供 Http 接口支持？

参考：https://github.com/lanaqi-opensource/autox-typescript-template

**Comment by SuperMonster003** [comment]
未来将考虑实现上述接口对接, 但开发周期可能相对较长, 请关注后续版本更新.
