### ISSUE TITLE
toast 有问题，有时候不显示

### ISSUE THREAD

**Issue by CuteLicense** [SuperMonster003/AutoJs6#67]
```
toastLog('##**全部任务执行完毕**##')
sleep(3e3);
toast('全部任务执行完毕，即将退出...', true);    /* 显示消息框 3.5 秒钟. */
sleep(4e3);

```
第一次执行正常，重复执行时 toastLog、toast 随机不显示

**Comment by SuperMonster003** [comment]
如果 `device.sdkInt` 返回值为 `28`, 或者使用 `鸿蒙 (HarmonyOS) 2` 操作系统, 将可能出现 toast 功能异常.
参阅 [消息浮动框 (Toast)](https://docs.autojs6.com/#/toast) 章节的序言部分.

若实际情况与上述情形均不相符, 请提供详细的问题描述 (如: 重复执行是指重复执行文件还是将代码放在循环体内; 不含 sleep 阻塞的 toast 测试; 导致异常必定复现的示例代码; 等).

**Comment by CuteLicense** [comment]
device.sdkInt 返回值为 33
操作过程： 
vscode 中运行上面脚本，提示结束后，马上重新运行，如此重复。
在手机端运行较长的代码最后加上上述代码时会出现不显示的情况，我在进一步排查。
在手机端单独运行上述代码时，正常

**Comment by dqss** [comment]
我试过好像是传入的参数太多，只能传入一个，log的话可以多个,

**Comment by SuperMonster003** [comment]
后续版本 (v6.3.4+) 会尝试将 toast 模块的实例暂存级别由 `脚本运行时 (ScriptRuntime)` 级别上升至 `应用 (Application)` 级别, 以解决上述问题, 请关注后续版本更新.

**Comment by SuperMonster003** [comment]
6.4.0 已尝试对上述问题做出优化, 如仍有问题, 可继续反馈.

此 issue 暂时关闭.
