### ISSUE TITLE
newWebSocket没有失败重连的方法

### ISSUE THREAD

**Issue by vipterry** [SuperMonster003/AutoJs6#69]
你好，在使用的中途发现没有重新连接的方法（很多时候由于网络或者其它原因导致连接断开之后，没有办法让当前实例直接重新连接），建议增加connect方法：
<img width="319" alt="image" src="https://github.com/SuperMonster003/AutoJs6/assets/7145196/8028c8bc-2ef1-4c1f-8990-afb6974c371b">

**Comment by SuperMonster003** [comment]
WebSocket 本身没有重连的方法, 网络上实现的重连方式, 一般都是包装一套完整的连接建立方法, 重连相当于重新按原有的包装参数创建新的连接.

下一版 AutoJs6 将提供 rebuild 方法, 实现类似上述重连方式的封装.

另如有更好的实现思路或其他相关建议, 可继续反馈.

**Comment by SuperMonster003** [comment]
`ws.rebuild()` 可重建连接 (通过使用原始配置重建实例实现).

通常 `rebuild` 方法在 `ws.on('xxx')` 事件回调方法中使用, 可能造成无限循环.  
可使用 maxRebuildTimes 参数 (number 类型) 限制最大重连次数, 如 `ws.rebuild(5)`.

`rebuild` 方法的功能及内部实现目前均不够完善, 如有更好的建议或使用时有任何问题, 可在此继续反馈, 我会根据反馈尝试修复或继续优化这个重连方法.
