### ISSUE TITLE
希望能添加一下加密支持模块

### ISSUE THREAD

**Issue by aqen** [SuperMonster003/AutoJs6#70]

**Comment by SuperMonster003** [comment]
是类似 Auto.js Pro 的 crypto 模块吗.  
如果不是, 请提供更详细的信息, 或相关示例代码.

**Comment by aqen** [comment]
> 是类似 Auto.js Pro 的 crypto 模块吗. 如果不是, 请提供更详细的信息, 或相关示例代码.

是的
类似Auto.js Pro 的 crypto模块
Autox.js 中也有。
