### ISSUE TITLE
请教 automator.captureScreen() 截图后的结果转换（Hardware bitmaps）

### ISSUE THREAD

**Issue by CuteLicense** [SuperMonster003/AutoJs6#73]
示例中的辅助功能截图，这个截图返回的不同于使用截图权限截图后的返回结果，错误提示：unable to getPixel(), pixel access is not supported on Config#HARDWARE bitmaps
请问有转换函数吗？谢谢！
```
requestScreenCapture(true);
var img = captureScreen();
var color = images.pixel(img, 100, 100);
toast(colors.toString(color));

let capt = automator.captureScreen();
color = images.pixel(capt, 100, 100);
toast(colors.toString(color));
```

**Comment by SuperMonster003** [comment]
将在下一版本修复上述问题.

不过无障碍截图目前仅能支持纵向截图, 即使 `requestScreenCapture` 传入了 `true` 参数.

另外解决方案可参考以下网址:  
https://stackoverflow.com/questions/60462841

**Comment by CuteLicense** [comment]
> 将在下一版本修复上述问题.
> 
> 不过无障碍截图目前仅能支持纵向截图, 即使 `requestScreenCapture` 传入了 `true` 参数.
> 
> 另外解决方案可参考以下网址: https://stackoverflow.com/questions/60462841

谢谢！
参照临时解决了：
```
var captNew = ImageWrapper.ofBitmap(capt.bitmap.copy(Bitmap.Config.RGBA_F16, true));
var color = images.pixel(captNew, 100, 100);
```
