### ISSUE TITLE
项目运行有点疑问

### ISSUE THREAD

**Issue by AdminQQZ** [SuperMonster003/AutoJs6#74]
编译遇到的问题：  类文件具有错误的版本 63.0, 应为 61.0 （文件太多了，无法编译）请问这个怎么处理

Android stduio版本
![image](https://github.com/SuperMonster003/AutoJs6/assets/12959954/dc67055f-a7a6-4a86-a8e7-520cb2e86d2d)

**Comment by SuperMonster003** [comment]
打开 Android Studio 的配置 (快捷键 CTRL + ALT + S).
定位 File | Settings | Build, Execution, Deployment | Build Tools | Gradle.
确保右侧窗口的 Gradle JDK 不低于 19.

![image](https://github.com/SuperMonster003/AutoJs6/assets/30370009/137e510f-fdc4-43ff-9bc7-0f44230db647)

**Comment by AdminQQZ** [comment]
good
