### ISSUE TITLE
悬浮窗工具看不到

### ISSUE THREAD

**Issue by LYS86** [SuperMonster003/AutoJs6#90]
悬浮窗工具不会自适应位置，如果当前悬浮窗位于中下部，从竖屏转换到横屏时，无法找到悬浮窗

**Comment by LYS86** [comment]
![Screenshot_2023-07-07-09-23-51-348_com microsoft emmx](https://github.com/SuperMonster003/AutoJs6/assets/106499400/d68846e9-8ba0-4037-a836-66e4f49646b0)

**Comment by SuperMonster003** [comment]
感谢反馈, 将于 6.3.4 尝试修复上述问题.

**Comment by SuperMonster003** [comment]
6.4.0 已尝试修复上述问题. 如问题复现, 可继续反馈.

此 issue 暂时关闭.

**Comment by LYS86** [comment]
已修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月2日(周四) 晚上10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SuperMonster003/AutoJs6] 悬浮窗工具看不到 (Issue #90)




 
6.4.0 已尝试修复上述问题. 如问题复现, 可继续反馈.
 
此 issue 暂时关闭.
