### ISSUE TITLE
vscode按F6运行的时候就断开连接

### ISSUE THREAD

**Issue by da1995** [SuperMonster003/AutoJs6#93]
服务端，客户端，ADB，三种方式，都试了，按F6就断开，autojs6会提示 
Unknown data type (4) for message dispatching

**Comment by da1995** [comment]
![Uploading 微信图片_20230708104336.jpg…]()

**Comment by da1995** [comment]
![微信图片_20230708104336](https://github.com/SuperMonster003/AutoJs6/assets/81143047/7cf87b2b-9dde-4064-a5af-ebe75cdec0ae)

**Comment by da1995** [comment]
运行环境：windows10
手机环境：安卓13，红米K50U，MIUI14

**Comment by da1995** [comment]
解决方案回退 6.3.1，vscode回退1.0.4
恢复正常

**Comment by wanshi1024** [comment]
已解决 感谢  还有一个问题就是图标的叉号点击说   无运行中的脚本  但是明明有运行

**Comment by SuperMonster003** [comment]
#91 #92
