### ISSUE TITLE
autojs6-v6.3.2 连接pc后无法保存电脑文件到手机

### ISSUE THREAD

**Issue by hongfengfeiyang999** [SuperMonster003/AutoJs6#94]
autojs6-v6.3.2 手机版更新后，电脑的Visual Studio Code 也已更新插件最新版，但是无法同步电脑文件到手机，同步的时候会提示
Unknown data type (0) for message dispatching

**Comment by wanshi1024** [comment]
我也发现了

**Comment by SuperMonster003** [comment]
#91 #92 #93
