### ISSUE TITLE
崩溃了  这个websocket一接收信息就报错到底为什么

### ISSUE THREAD

**Issue by wanshi1024** [SuperMonster003/AutoJs6#96]
`22:00:54.781/D: WebSocket failure
22:00:54.783/D: org.autojs.autojs.runtime.exception.ScriptInterruptedException null org.autojs.autojs.core.web.WebSocket@ffaca2e`

**Comment by SuperMonster003** [comment]
提供的反馈信息不足以排查问题, 请提供更详细的信息, 如关键示例代码, 异常触发条件, 更完整的脚本运行日志等.
